service: reviews
runtime: python311

basic_scaling:
    max_instances: 2
    idle_timeout: 10m

resources:
    cpu: 4
    memory_gb: 2
    disk_size_gb: 10

entrypoint: gunicorn -b 0.0.0.0:8080 index:server




