name: word
channels:
  - conda-forge
dependencies:
  - python
  - dash
  - dash-bootstrap-components
  - dash-html-components
  - dash-table
  - Flask
  - gunicorn
  - itsdangerous
  - Jinja2
  - plotly
  - numpy
  - pandas
  - Werkzeug
  - pip
  - python-dotenv
  - dash-auth
  - wordcloud
  - gensim
  - pip:
      - dash-ag-grid
      - spacy
